### ISSUE TITLE
No Module Named 'setuptools'

### ISSUE THREAD

**Issue by jeffkerby** [botnet88/Recordurbate-streamlink#2]
While running sudo python3 setup.py install I receive the following error:

File "setup.py", line 6 in <module>
from setuptools import setup, find_packages
ImportError: No module named 'setuptools' 

How to resolve?

**Comment by botnet88** [comment]
You need to install python3-setuptools. If you are using a Debian based system you can run `sudo apt install python3-setuptools`. On an Arch based system use `sudo pacman -S python-setuptools`.
